server:
  port: 8761

spring:
  application:
    name: example-eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

zuul:
  prefix: /
  routes:
    example-app-one:
      path: /one/**
      url:  http://localhost:8081
    example-app-two:
      path: /two/**
      url:  http://localhost:8082
